### ISSUE TITLE
A very poor initial experience

### ISSUE THREAD

**Issue by jonhiggs** [akamai-open/edgegrid-curl#10]
``` ShellSession
  $ ./egcurl
  Traceback (most recent call last):
    File "./egcurl", line 402, in <module>
      sys.exit(main())
    File "./egcurl", line 385, in main
      url = args[-1]
  IndexError: list index out of range
```

``` ShellSession
  $ ./egcurl --help
  Traceback (most recent call last):
    File "./egcurl", line 402, in <module>
      sys.exit(main())
    File "./egcurl", line 382, in main
      rv, args = parse_arguments(argv[1:])
    File "./egcurl", line 219, in parse_arguments
      log.error(usage)
  NameError: global name 'usage' is not defined
```

``` ShellSession
  $ ./egcurl www.google.com
  Traceback (most recent call last):
    File "./egcurl", line 402, in <module>
      sys.exit(main())
    File "./egcurl", line 387, in main
      config = parse_configuration(host)
    File "./egcurl", line 307, in parse_configuration
      with open(config_path, "r") as f:
  IOError: [Errno 2] No such file or directory: '/Users/jon.higgs/.egcurl'
```

'nough said.

**Comment by elreydetodo** [comment]
Yeah, that was not really very good behavior. We've started using `argparse` now so that `./egcurl --help` works, and you automatically get the short-form help in the absence of any arguments. The newest version should be much more helpful at getting started.
